`timescale 1ns / 1ps

module interface_gtx_8ch(
    // system
    input  wire [7:0] rx_pma_rst_n,

    // 100MHz DRP clock
    input  wire clk_drp_100M,

    // 125MHz GTX ref clock
    input  wire clk_gtx_125M,

    // GTX IO
    output wire [7:0] gtx_tx_p,
                      gtx_tx_n,
    input  wire [7:0] gtx_rx_p,
                      gtx_rx_n,

    // 125MHz TX, RX out clock
    output wire [7:0] clk_txoutclk_bufg,
                      clk_rxoutclk_bufg,

    // GTX data
    input  wire [127:0] gt_tx_data,
    input  wire [7:0] gt_tx_data_valid,
    output wire [127:0] gt_rx_data,
    output wire [7:0] gt_rx_data_valid,

    // states for alignment
    output wire [7:0] gtx_cpll_is_lock,
    output wire [7:0] rx_reset_done,
    output wire [15:0] rx_data_is_comma,
    output wire [7:0] gtx_rx_error
    );

    // txoutclk / rxoutclk buffers
    wire clk_txoutclk [0:7];
    wire clk_rxoutclk [0:7];

    genvar i;
    generate
        for (i = 0; i < 8; i = i + 1) begin : gen_bufg
            BUFG instance_bufg_txoutclk(
                .I (clk_txoutclk[i]),
                .O (clk_txoutclk_bufg[i])
            );
            BUFG instance_bufg_rxoutclk(
                .I (clk_rxoutclk[i]),
                .O (clk_rxoutclk_bufg[i])
            );
        end
    endgenerate

    // flags
    wire [1:0] tx_data_is_k [0:7];
    wire [1:0] rx_data_is_k [0:7];
    wire [1:0] rx_not_in_table [0:7];

    generate
        for (i = 0; i < 8; i = i + 1) begin : gen_flags
            assign tx_data_is_k[i] = gt_tx_data_valid[i] ? 2'b00 : 2'b11;
            assign gt_rx_data_valid[i] = (rx_data_is_k[i] == 2'b00) ? 1 : 0;
            assign gtx_rx_error[i] = |rx_not_in_table[i];
        end
    endgenerate

    gtx_phy_8ch instance_gtx_phy_8ch (
        // system
        .sysclk_in                      (clk_drp_100M),
        .soft_reset_tx_in               (1'b0),
        .soft_reset_rx_in               (1'b0),
        .dont_reset_on_data_error_in    (1'b0),
        .gt0_tx_fsm_reset_done_out      (),
        .gt0_rx_fsm_reset_done_out      (),
        .gt0_data_valid_in              (1'b1),
        .gt1_tx_fsm_reset_done_out      (),
        .gt1_rx_fsm_reset_done_out      (),
        .gt1_data_valid_in              (1'b1),
        .gt2_tx_fsm_reset_done_out      (),
        .gt2_rx_fsm_reset_done_out      (),
        .gt2_data_valid_in              (1'b1),
        .gt3_tx_fsm_reset_done_out      (),
        .gt3_rx_fsm_reset_done_out      (),
        .gt3_data_valid_in              (1'b1),
        .gt4_tx_fsm_reset_done_out      (),
        .gt4_rx_fsm_reset_done_out      (),
        .gt4_data_valid_in              (1'b1),
        .gt5_tx_fsm_reset_done_out      (),
        .gt5_rx_fsm_reset_done_out      (),
        .gt5_data_valid_in              (1'b1),
        .gt6_tx_fsm_reset_done_out      (),
        .gt6_rx_fsm_reset_done_out      (),
        .gt6_data_valid_in              (1'b1),
        .gt7_tx_fsm_reset_done_out      (),
        .gt7_rx_fsm_reset_done_out      (),
        .gt7_data_valid_in              (1'b1),

        //GT0  (X1Y4)
        //------------------------------- CPLL Ports -------------------------------
        .gt0_cpllfbclklost_out          (),
        .gt0_cplllock_out               (gtx_cpll_is_lock[0]),
        .gt0_cplllockdetclk_in          (clk_drp_100M),
        .gt0_cpllreset_in               (1'b0),
        //------------------------ Channel - Clocking Ports ------------------------
        .gt0_gtrefclk0_in               (1'b0),
        .gt0_gtrefclk1_in               (clk_gtx_125M),
        //-------------------------- Channel - DRP Ports  --------------------------
        .gt0_drpaddr_in                 (9'b0),
        .gt0_drpclk_in                  (clk_drp_100M),
        .gt0_drpdi_in                   (16'b0),
        .gt0_drpdo_out                  (),
        .gt0_drpen_in                   (1'b0),
        .gt0_drprdy_out                 (),
        .gt0_drpwe_in                   (1'b0),
        //------------------------- Digital Monitor Ports --------------------------
        .gt0_dmonitorout_out            (),
        //---------------------------- Power-Down Ports ----------------------------
        .gt0_rxpd_in                    (2'b0),
        .gt0_txpd_in                    (2'b0),
        //------------------- RX Initialization and Reset Ports --------------------
        .gt0_eyescanreset_in            (1'b0),
        .gt0_rxuserrdy_in               (1'b1),
        //------------------------ RX Margin Analysis Ports ------------------------
        .gt0_eyescandataerror_out       (),
        .gt0_eyescantrigger_in          (1'b0),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .gt0_rxusrclk_in                (clk_rxoutclk_bufg[0]),
        .gt0_rxusrclk2_in               (clk_rxoutclk_bufg[0]),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .gt0_rxdata_out                 (gt_rx_data[0 +: 16]),
        //---------------- Receive Ports - RX 8B/10B Decoder Ports -----------------
        .gt0_rxdisperr_out              (),
        .gt0_rxnotintable_out           (rx_not_in_table[0]),
        //------------------------- Receive Ports - RX AFE -------------------------
        .gt0_gtxrxp_in                  (gtx_rx_p[0]),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gt0_gtxrxn_in                  (gtx_rx_n[0]),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .gt0_rxphmonitor_out            (),
        .gt0_rxphslipmonitor_out        (),
        //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
        .gt0_rxbyteisaligned_out        (),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .gt0_rxdfelpmreset_in           (1'b0),
        .gt0_rxmonitorout_out           (),
        .gt0_rxmonitorsel_in            (2'b0),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .gt0_rxoutclk_out               (clk_rxoutclk[0]),
        .gt0_rxoutclkfabric_out         (),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gt0_gtrxreset_in               (1'b0),
        .gt0_rxpmareset_in              (~rx_pma_rst_n[0]),    // important
        //----------------- Receive Ports - RX8B/10B Decoder Ports -----------------
        .gt0_rxchariscomma_out          (rx_data_is_comma[0 +: 2]),
        .gt0_rxcharisk_out              (rx_data_is_k[0]),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .gt0_rxresetdone_out            (rx_reset_done[0]),
        //------------------- TX Initialization and Reset Ports --------------------
        .gt0_gttxreset_in               (1'b0),
        .gt0_txuserrdy_in               (1'b1),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .gt0_txusrclk_in                (clk_txoutclk_bufg[0]),
        .gt0_txusrclk2_in               (clk_txoutclk_bufg[0]),
        //------------------- Transmit Ports - PCI Express Ports -------------------
        .gt0_txelecidle_in              (1'b0),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .gt0_txdata_in                  (gt_tx_data[0 +: 16]),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gt0_gtxtxn_out                 (gtx_tx_n[0]),
        .gt0_gtxtxp_out                 (gtx_tx_p[0]),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .gt0_txoutclk_out               (clk_txoutclk[0]),
        .gt0_txoutclkfabric_out         (),
        .gt0_txoutclkpcs_out            (),
        //------------------- Transmit Ports - TX Gearbox Ports --------------------
        .gt0_txcharisk_in               (tx_data_is_k[0]),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .gt0_txresetdone_out            (),

        //GT1  (X1Y5)
        .gt1_cpllfbclklost_out          (),
        .gt1_cplllock_out               (gtx_cpll_is_lock[1]),
        .gt1_cplllockdetclk_in          (clk_drp_100M),
        .gt1_cpllreset_in               (1'b0),
        .gt1_gtrefclk0_in               (1'b0),
        .gt1_gtrefclk1_in               (clk_gtx_125M),
        .gt1_drpaddr_in                 (9'b0),
        .gt1_drpclk_in                  (clk_drp_100M),
        .gt1_drpdi_in                   (16'b0),
        .gt1_drpdo_out                  (),
        .gt1_drpen_in                   (1'b0),
        .gt1_drprdy_out                 (),
        .gt1_drpwe_in                   (1'b0),
        .gt1_dmonitorout_out            (),
        .gt1_rxpd_in                    (2'b0),
        .gt1_txpd_in                    (2'b0),
        .gt1_eyescanreset_in            (1'b0),
        .gt1_rxuserrdy_in               (1'b1),
        .gt1_eyescandataerror_out       (),
        .gt1_eyescantrigger_in          (1'b0),
        .gt1_rxusrclk_in                (clk_rxoutclk_bufg[1]),
        .gt1_rxusrclk2_in               (clk_rxoutclk_bufg[1]),
        .gt1_rxdata_out                 (gt_rx_data[16 +: 16]),
        .gt1_rxdisperr_out              (),
        .gt1_rxnotintable_out           (rx_not_in_table[1]),
        .gt1_gtxrxp_in                  (gtx_rx_p[1]),
        .gt1_gtxrxn_in                  (gtx_rx_n[1]),
        .gt1_rxphmonitor_out            (),
        .gt1_rxphslipmonitor_out        (),
        .gt1_rxbyteisaligned_out        (),
        .gt1_rxdfelpmreset_in           (1'b0),
        .gt1_rxmonitorout_out           (),
        .gt1_rxmonitorsel_in            (2'b0),
        .gt1_rxoutclk_out               (clk_rxoutclk[1]),
        .gt1_rxoutclkfabric_out         (),
        .gt1_gtrxreset_in               (1'b0),
        .gt1_rxpmareset_in              (~rx_pma_rst_n[1]),    // important
        .gt1_rxchariscomma_out          (rx_data_is_comma[2 +: 2]),
        .gt1_rxcharisk_out              (rx_data_is_k[1]),
        .gt1_rxresetdone_out            (rx_reset_done[1]),
        .gt1_gttxreset_in               (1'b0),
        .gt1_txuserrdy_in               (1'b1),
        .gt1_txusrclk_in                (clk_txoutclk_bufg[1]),
        .gt1_txusrclk2_in               (clk_txoutclk_bufg[1]),
        .gt1_txelecidle_in              (1'b0),
        .gt1_txdata_in                  (gt_tx_data[16 +: 16]),
        .gt1_gtxtxn_out                 (gtx_tx_n[1]),
        .gt1_gtxtxp_out                 (gtx_tx_p[1]),
        .gt1_txoutclk_out               (clk_txoutclk[1]),
        .gt1_txoutclkfabric_out         (),
        .gt1_txoutclkpcs_out            (),
        .gt1_txcharisk_in               (tx_data_is_k[1]),
        .gt1_txresetdone_out            (),

        //GT2  (X1Y6)
        .gt2_cpllfbclklost_out          (),
        .gt2_cplllock_out               (gtx_cpll_is_lock[2]),
        .gt2_cplllockdetclk_in          (clk_drp_100M),
        .gt2_cpllreset_in               (1'b0),
        .gt2_gtrefclk0_in               (1'b0),
        .gt2_gtrefclk1_in               (clk_gtx_125M),
        .gt2_drpaddr_in                 (9'b0),
        .gt2_drpclk_in                  (clk_drp_100M),
        .gt2_drpdi_in                   (16'b0),
        .gt2_drpdo_out                  (),
        .gt2_drpen_in                   (1'b0),
        .gt2_drprdy_out                 (),
        .gt2_drpwe_in                   (1'b0),
        .gt2_dmonitorout_out            (),
        .gt2_rxpd_in                    (2'b0),
        .gt2_txpd_in                    (2'b0),
        .gt2_eyescanreset_in            (1'b0),
        .gt2_rxuserrdy_in               (1'b1),
        .gt2_eyescandataerror_out       (),
        .gt2_eyescantrigger_in          (1'b0),
        .gt2_rxusrclk_in                (clk_rxoutclk_bufg[2]),
        .gt2_rxusrclk2_in               (clk_rxoutclk_bufg[2]),
        .gt2_rxdata_out                 (gt_rx_data[32 +: 16]),
        .gt2_rxdisperr_out              (),
        .gt2_rxnotintable_out           (rx_not_in_table[2]),
        .gt2_gtxrxp_in                  (gtx_rx_p[2]),
        .gt2_gtxrxn_in                  (gtx_rx_n[2]),
        .gt2_rxphmonitor_out            (),
        .gt2_rxphslipmonitor_out        (),
        .gt2_rxbyteisaligned_out        (),
        .gt2_rxdfelpmreset_in           (1'b0),
        .gt2_rxmonitorout_out           (),
        .gt2_rxmonitorsel_in            (2'b0),
        .gt2_rxoutclk_out               (clk_rxoutclk[2]),
        .gt2_rxoutclkfabric_out         (),
        .gt2_gtrxreset_in               (1'b0),
        .gt2_rxpmareset_in              (~rx_pma_rst_n[2]),    // important
        .gt2_rxchariscomma_out          (rx_data_is_comma[4 +: 2]),
        .gt2_rxcharisk_out              (rx_data_is_k[2]),
        .gt2_rxresetdone_out            (rx_reset_done[2]),
        .gt2_gttxreset_in               (1'b0),
        .gt2_txuserrdy_in               (1'b1),
        .gt2_txusrclk_in                (clk_txoutclk_bufg[2]),
        .gt2_txusrclk2_in               (clk_txoutclk_bufg[2]),
        .gt2_txelecidle_in              (1'b0),
        .gt2_txdata_in                  (gt_tx_data[32 +: 16]),
        .gt2_gtxtxn_out                 (gtx_tx_n[2]),
        .gt2_gtxtxp_out                 (gtx_tx_p[2]),
        .gt2_txoutclk_out               (clk_txoutclk[2]),
        .gt2_txoutclkfabric_out         (),
        .gt2_txoutclkpcs_out            (),
        .gt2_txcharisk_in               (tx_data_is_k[2]),
        .gt2_txresetdone_out            (),

        //GT3  (X1Y7)
        .gt3_cpllfbclklost_out          (),
        .gt3_cplllock_out               (gtx_cpll_is_lock[3]),
        .gt3_cplllockdetclk_in          (clk_drp_100M),
        .gt3_cpllreset_in               (1'b0),
        .gt3_gtrefclk0_in               (1'b0),
        .gt3_gtrefclk1_in               (clk_gtx_125M),
        .gt3_drpaddr_in                 (9'b0),
        .gt3_drpclk_in                  (clk_drp_100M),
        .gt3_drpdi_in                   (16'b0),
        .gt3_drpdo_out                  (),
        .gt3_drpen_in                   (1'b0),
        .gt3_drprdy_out                 (),
        .gt3_drpwe_in                   (1'b0),
        .gt3_dmonitorout_out            (),
        .gt3_rxpd_in                    (2'b0),
        .gt3_txpd_in                    (2'b0),
        .gt3_eyescanreset_in            (1'b0),
        .gt3_rxuserrdy_in               (1'b1),
        .gt3_eyescandataerror_out       (),
        .gt3_eyescantrigger_in          (1'b0),
        .gt3_rxusrclk_in                (clk_rxoutclk_bufg[3]),
        .gt3_rxusrclk2_in               (clk_rxoutclk_bufg[3]),
        .gt3_rxdata_out                 (gt_rx_data[48 +: 16]),
        .gt3_rxdisperr_out              (),
        .gt3_rxnotintable_out           (rx_not_in_table[3]),
        .gt3_gtxrxp_in                  (gtx_rx_p[3]),
        .gt3_gtxrxn_in                  (gtx_rx_n[3]),
        .gt3_rxphmonitor_out            (),
        .gt3_rxphslipmonitor_out        (),
        .gt3_rxbyteisaligned_out        (),
        .gt3_rxdfelpmreset_in           (1'b0),
        .gt3_rxmonitorout_out           (),
        .gt3_rxmonitorsel_in            (2'b0),
        .gt3_rxoutclk_out               (clk_rxoutclk[3]),
        .gt3_rxoutclkfabric_out         (),
        .gt3_gtrxreset_in               (1'b0),
        .gt3_rxpmareset_in              (~rx_pma_rst_n[3]),    // important
        .gt3_rxchariscomma_out          (rx_data_is_comma[6 +: 2]),
        .gt3_rxcharisk_out              (rx_data_is_k[3]),
        .gt3_rxresetdone_out            (rx_reset_done[3]),
        .gt3_gttxreset_in               (1'b0),
        .gt3_txuserrdy_in               (1'b1),
        .gt3_txusrclk_in                (clk_txoutclk_bufg[3]),
        .gt3_txusrclk2_in               (clk_txoutclk_bufg[3]),
        .gt3_txelecidle_in              (1'b0),
        .gt3_txdata_in                  (gt_tx_data[48 +: 16]),
        .gt3_gtxtxn_out                 (gtx_tx_n[3]),
        .gt3_gtxtxp_out                 (gtx_tx_p[3]),
        .gt3_txoutclk_out               (clk_txoutclk[3]),
        .gt3_txoutclkfabric_out         (),
        .gt3_txoutclkpcs_out            (),
        .gt3_txcharisk_in               (tx_data_is_k[3]),
        .gt3_txresetdone_out            (),

        //GT4  (X1Y12)
        .gt4_cpllfbclklost_out          (),
        .gt4_cplllock_out               (gtx_cpll_is_lock[4]),
        .gt4_cplllockdetclk_in          (clk_drp_100M),
        .gt4_cpllreset_in               (1'b0),
        .gt4_gtrefclk0_in               (1'b0),
        .gt4_gtrefclk1_in               (clk_gtx_125M),
        .gt4_drpaddr_in                 (9'b0),
        .gt4_drpclk_in                  (clk_drp_100M),
        .gt4_drpdi_in                   (16'b0),
        .gt4_drpdo_out                  (),
        .gt4_drpen_in                   (1'b0),
        .gt4_drprdy_out                 (),
        .gt4_drpwe_in                   (1'b0),
        .gt4_dmonitorout_out            (),
        .gt4_rxpd_in                    (2'b0),
        .gt4_txpd_in                    (2'b0),
        .gt4_eyescanreset_in            (1'b0),
        .gt4_rxuserrdy_in               (1'b1),
        .gt4_eyescandataerror_out       (),
        .gt4_eyescantrigger_in          (1'b0),
        .gt4_rxusrclk_in                (clk_rxoutclk_bufg[4]),
        .gt4_rxusrclk2_in               (clk_rxoutclk_bufg[4]),
        .gt4_rxdata_out                 (gt_rx_data[64 +: 16]),
        .gt4_rxdisperr_out              (),
        .gt4_rxnotintable_out           (rx_not_in_table[4]),
        .gt4_gtxrxp_in                  (gtx_rx_p[4]),
        .gt4_gtxrxn_in                  (gtx_rx_n[4]),
        .gt4_rxphmonitor_out            (),
        .gt4_rxphslipmonitor_out        (),
        .gt4_rxbyteisaligned_out        (),
        .gt4_rxdfelpmreset_in           (1'b0),
        .gt4_rxmonitorout_out           (),
        .gt4_rxmonitorsel_in            (2'b0),
        .gt4_rxoutclk_out               (clk_rxoutclk[4]),
        .gt4_rxoutclkfabric_out         (),
        .gt4_gtrxreset_in               (1'b0),
        .gt4_rxpmareset_in              (~rx_pma_rst_n[4]),    // important
        .gt4_rxchariscomma_out          (rx_data_is_comma[8 +: 2]),
        .gt4_rxcharisk_out              (rx_data_is_k[4]),
        .gt4_rxresetdone_out            (rx_reset_done[4]),
        .gt4_gttxreset_in               (1'b0),
        .gt4_txuserrdy_in               (1'b1),
        .gt4_txusrclk_in                (clk_txoutclk_bufg[4]),
        .gt4_txusrclk2_in               (clk_txoutclk_bufg[4]),
        .gt4_txelecidle_in              (1'b0),
        .gt4_txdata_in                  (gt_tx_data[64 +: 16]),
        .gt4_gtxtxn_out                 (gtx_tx_n[4]),
        .gt4_gtxtxp_out                 (gtx_tx_p[4]),
        .gt4_txoutclk_out               (clk_txoutclk[4]),
        .gt4_txoutclkfabric_out         (),
        .gt4_txoutclkpcs_out            (),
        .gt4_txcharisk_in               (tx_data_is_k[4]),
        .gt4_txresetdone_out            (),

        //GT5  (X1Y13)
        .gt5_cpllfbclklost_out          (),
        .gt5_cplllock_out               (gtx_cpll_is_lock[5]),
        .gt5_cplllockdetclk_in          (clk_drp_100M),
        .gt5_cpllreset_in               (1'b0),
        .gt5_gtrefclk0_in               (1'b0),
        .gt5_gtrefclk1_in               (clk_gtx_125M),
        .gt5_drpaddr_in                 (9'b0),
        .gt5_drpclk_in                  (clk_drp_100M),
        .gt5_drpdi_in                   (16'b0),
        .gt5_drpdo_out                  (),
        .gt5_drpen_in                   (1'b0),
        .gt5_drprdy_out                 (),
        .gt5_drpwe_in                   (1'b0),
        .gt5_dmonitorout_out            (),
        .gt5_rxpd_in                    (2'b0),
        .gt5_txpd_in                    (2'b0),
        .gt5_eyescanreset_in            (1'b0),
        .gt5_rxuserrdy_in               (1'b1),
        .gt5_eyescandataerror_out       (),
        .gt5_eyescantrigger_in          (1'b0),
        .gt5_rxusrclk_in                (clk_rxoutclk_bufg[5]),
        .gt5_rxusrclk2_in               (clk_rxoutclk_bufg[5]),
        .gt5_rxdata_out                 (gt_rx_data[80 +: 16]),
        .gt5_rxdisperr_out              (),
        .gt5_rxnotintable_out           (rx_not_in_table[5]),
        .gt5_gtxrxp_in                  (gtx_rx_p[5]),
        .gt5_gtxrxn_in                  (gtx_rx_n[5]),
        .gt5_rxphmonitor_out            (),
        .gt5_rxphslipmonitor_out        (),
        .gt5_rxbyteisaligned_out        (),
        .gt5_rxdfelpmreset_in           (1'b0),
        .gt5_rxmonitorout_out           (),
        .gt5_rxmonitorsel_in            (2'b0),
        .gt5_rxoutclk_out               (clk_rxoutclk[5]),
        .gt5_rxoutclkfabric_out         (),
        .gt5_gtrxreset_in               (1'b0),
        .gt5_rxpmareset_in              (~rx_pma_rst_n[5]),    // important
        .gt5_rxchariscomma_out          (rx_data_is_comma[10 +: 2]),
        .gt5_rxcharisk_out              (rx_data_is_k[5]),
        .gt5_rxresetdone_out            (rx_reset_done[5]),
        .gt5_gttxreset_in               (1'b0),
        .gt5_txuserrdy_in               (1'b1),
        .gt5_txusrclk_in                (clk_txoutclk_bufg[5]),
        .gt5_txusrclk2_in               (clk_txoutclk_bufg[5]),
        .gt5_txelecidle_in              (1'b0),
        .gt5_txdata_in                  (gt_tx_data[80 +: 16]),
        .gt5_gtxtxn_out                 (gtx_tx_n[5]),
        .gt5_gtxtxp_out                 (gtx_tx_p[5]),
        .gt5_txoutclk_out               (clk_txoutclk[5]),
        .gt5_txoutclkfabric_out         (),
        .gt5_txoutclkpcs_out            (),
        .gt5_txcharisk_in               (tx_data_is_k[5]),
        .gt5_txresetdone_out            (),

        //GT6  (X1Y14)
        .gt6_cpllfbclklost_out          (),
        .gt6_cplllock_out               (gtx_cpll_is_lock[6]),
        .gt6_cplllockdetclk_in          (clk_drp_100M),
        .gt6_cpllreset_in               (1'b0),
        .gt6_gtrefclk0_in               (1'b0),
        .gt6_gtrefclk1_in               (clk_gtx_125M),
        .gt6_drpaddr_in                 (9'b0),
        .gt6_drpclk_in                  (clk_drp_100M),
        .gt6_drpdi_in                   (16'b0),
        .gt6_drpdo_out                  (),
        .gt6_drpen_in                   (1'b0),
        .gt6_drprdy_out                 (),
        .gt6_drpwe_in                   (1'b0),
        .gt6_dmonitorout_out            (),
        .gt6_rxpd_in                    (2'b0),
        .gt6_txpd_in                    (2'b0),
        .gt6_eyescanreset_in            (1'b0),
        .gt6_rxuserrdy_in               (1'b1),
        .gt6_eyescandataerror_out       (),
        .gt6_eyescantrigger_in          (1'b0),
        .gt6_rxusrclk_in                (clk_rxoutclk_bufg[6]),
        .gt6_rxusrclk2_in               (clk_rxoutclk_bufg[6]),
        .gt6_rxdata_out                 (gt_rx_data[96 +: 16]),
        .gt6_rxdisperr_out              (),
        .gt6_rxnotintable_out           (rx_not_in_table[6]),
        .gt6_gtxrxp_in                  (gtx_rx_p[6]),
        .gt6_gtxrxn_in                  (gtx_rx_n[6]),
        .gt6_rxphmonitor_out            (),
        .gt6_rxphslipmonitor_out        (),
        .gt6_rxbyteisaligned_out        (),
        .gt6_rxdfelpmreset_in           (1'b0),
        .gt6_rxmonitorout_out           (),
        .gt6_rxmonitorsel_in            (2'b0),
        .gt6_rxoutclk_out               (clk_rxoutclk[6]),
        .gt6_rxoutclkfabric_out         (),
        .gt6_gtrxreset_in               (1'b0),
        .gt6_rxpmareset_in              (~rx_pma_rst_n[6]),    // important
        .gt6_rxchariscomma_out          (rx_data_is_comma[12 +: 2]),
        .gt6_rxcharisk_out              (rx_data_is_k[6]),
        .gt6_rxresetdone_out            (rx_reset_done[6]),
        .gt6_gttxreset_in               (1'b0),
        .gt6_txuserrdy_in               (1'b1),
        .gt6_txusrclk_in                (clk_txoutclk_bufg[6]),
        .gt6_txusrclk2_in               (clk_txoutclk_bufg[6]),
        .gt6_txelecidle_in              (1'b0),
        .gt6_txdata_in                  (gt_tx_data[96 +: 16]),
        .gt6_gtxtxn_out                 (gtx_tx_n[6]),
        .gt6_gtxtxp_out                 (gtx_tx_p[6]),
        .gt6_txoutclk_out               (clk_txoutclk[6]),
        .gt6_txoutclkfabric_out         (),
        .gt6_txoutclkpcs_out            (),
        .gt6_txcharisk_in               (tx_data_is_k[6]),
        .gt6_txresetdone_out            (),

        //GT7  (X1Y15)
        .gt7_cpllfbclklost_out          (),
        .gt7_cplllock_out               (gtx_cpll_is_lock[7]),
        .gt7_cplllockdetclk_in          (clk_drp_100M),
        .gt7_cpllreset_in               (1'b0),
        .gt7_gtrefclk0_in               (1'b0),
        .gt7_gtrefclk1_in               (clk_gtx_125M),
        .gt7_drpaddr_in                 (9'b0),
        .gt7_drpclk_in                  (clk_drp_100M),
        .gt7_drpdi_in                   (16'b0),
        .gt7_drpdo_out                  (),
        .gt7_drpen_in                   (1'b0),
        .gt7_drprdy_out                 (),
        .gt7_drpwe_in                   (1'b0),
        .gt7_dmonitorout_out            (),
        .gt7_rxpd_in                    (2'b0),
        .gt7_txpd_in                    (2'b0),
        .gt7_eyescanreset_in            (1'b0),
        .gt7_rxuserrdy_in               (1'b1),
        .gt7_eyescandataerror_out       (),
        .gt7_eyescantrigger_in          (1'b0),
        .gt7_rxusrclk_in                (clk_rxoutclk_bufg[7]),
        .gt7_rxusrclk2_in               (clk_rxoutclk_bufg[7]),
        .gt7_rxdata_out                 (gt_rx_data[112 +: 16]),
        .gt7_rxdisperr_out              (),
        .gt7_rxnotintable_out           (rx_not_in_table[7]),
        .gt7_gtxrxp_in                  (gtx_rx_p[7]),
        .gt7_gtxrxn_in                  (gtx_rx_n[7]),
        .gt7_rxphmonitor_out            (),
        .gt7_rxphslipmonitor_out        (),
        .gt7_rxbyteisaligned_out        (),
        .gt7_rxdfelpmreset_in           (1'b0),
        .gt7_rxmonitorout_out           (),
        .gt7_rxmonitorsel_in            (2'b0),
        .gt7_rxoutclk_out               (clk_rxoutclk[7]),
        .gt7_rxoutclkfabric_out         (),
        .gt7_gtrxreset_in               (1'b0),
        .gt7_rxpmareset_in              (~rx_pma_rst_n[7]),    // important
        .gt7_rxchariscomma_out          (rx_data_is_comma[14 +: 2]),
        .gt7_rxcharisk_out              (rx_data_is_k[7]),
        .gt7_rxresetdone_out            (rx_reset_done[7]),
        .gt7_gttxreset_in               (1'b0),
        .gt7_txuserrdy_in               (1'b1),
        .gt7_txusrclk_in                (clk_txoutclk_bufg[7]),
        .gt7_txusrclk2_in               (clk_txoutclk_bufg[7]),
        .gt7_txelecidle_in              (1'b0),
        .gt7_txdata_in                  (gt_tx_data[112 +: 16]),
        .gt7_gtxtxn_out                 (gtx_tx_n[7]),
        .gt7_gtxtxp_out                 (gtx_tx_p[7]),
        .gt7_txoutclk_out               (clk_txoutclk[7]),
        .gt7_txoutclkfabric_out         (),
        .gt7_txoutclkpcs_out            (),
        .gt7_txcharisk_in               (tx_data_is_k[7]),
        .gt7_txresetdone_out            (),

        // common ports (CPLL-based, tie off QPLL)
        .gt0_qplloutclk_in              (1'b0),
        .gt0_qplloutrefclk_in           (1'b0),
        .gt1_qplloutclk_in              (1'b0),
        .gt1_qplloutrefclk_in           (1'b0)
    );
endmodule
